### ISSUE TITLE
Padding of images

### ISSUE THREAD

**Issue by horsto** [giakou4/pyfeats#10]
Thank you for providing this library! 
I just started using it, and I read this line in your demo code: 

https://github.com/giakou4/pyfeats/blob/dc0e2d1b3623aeb7f26c9777dafb491ecd961b9c/demo/demo.py#L44

I did not quite understand whether it is indeed necessary to pad images (why? to prevent edge artefacts?)? Thanks!

**Comment by giakou4** [comment]
This is done solely to ensure the perimeter calculation is accurate.

**Comment by horsto** [comment]
Thanks, ok!
