### ISSUE TITLE
gclm.py not working

### ISSUE THREAD

**Issue by elahe-badali** [giakou4/pyfeats#2]
Hi @giakou4,
Thankyou for your very useful functions.
in gclm.py i get this errors:
mahotas cant import.
and:
AttributeError: module 'mahotas' has no attribute 'features'.

**Comment by giakou4** [comment]
There are certain dependencies are described in requirements.txt. You need to install, among others, the mahotas library (see https://pypi.org/project/mahotas/).

**Comment by elahe-badali** [comment]
![image](https://user-images.githubusercontent.com/39738835/140744938-2f995375-578b-4f5f-89f3-80806b3d68c1.png)

I am using your codes on colab.

**Comment by elahe-badali** [comment]
![image](https://user-images.githubusercontent.com/39738835/140745431-7198a40a-efca-4c27-8267-8e8d3db96f21.png)

**Comment by giakou4** [comment]
Try changing version to 1.4.12 which is the latest. Otherwise try pip install mahotas and remove it from requirements.

**Comment by elahe-badali** [comment]
It's solved. i install packages in requirments.txt manually. Thankyou for your guidance.
