### ISSUE TITLE
Inconsistent GLSZM features

### ISSUE THREAD

**Issue by Mayur28** [giakou4/pyfeats#6]
Hi,

I am trying to perform texture analysis for an image and everything is working perfectly, however, I seem to be experiencing an inconsistency when computing the GLSZM features. Specifically, when I compute the features locally (on my personal computer), I get the correct results (as seen from the results on the left of the screenshot attached below) whereas when I try to build a Docker container and try to run it, I get a different set of GLSZM features for the same image (as shown to the right of the screenshot attached). I have ensured that I am using the same package versions locally and in the requirements.txt when building the docker container. Upon further inspection, it seems that it is only the following sub features that are causing the issue: (2) GLSZM_LargeZoneEmphasis, (10) Large Zone Lo wGray Level Emphasis, and (11) Large Zone High Gray Level Emphasis.

Unfortunately, I am unable to share the images that I am using, but the issue arises for the same 3 sub-features.

If you could assist with the issue mentioned above, it would be highly appreciated.
![image](https://user-images.githubusercontent.com/26574827/224666160-984ad572-fe28-4212-9b62-d9fc447f0914.png)

**Comment by giakou4** [comment]
I regret to inform you that due to my current work commitments, I am unable to continue maintaining the project at this time. However I could inform you that GLSZM is quite unstable due to the way it is calculated: e.g., different padding results in different results.
