### ISSUE TITLE
How to cite pyfeats package

### ISSUE THREAD

**Issue by korrahman** [giakou4/pyfeats#8]
Hey there!
first of all I want to say thank you about the great package for image feature extraction. keep it up!
I want to cite your package in our paper. can you guide us?
thanks

**Comment by giakou4** [comment]
Thank you for using _pyfeats_. Here is the corrected BibTeX format to cite _pyfeats_:

```bibtex
@misc{pyfeats2021giakoumoglou,  
     author = {Nikolaos Giakoumoglou},  
     title = {PyFeats: Open-source software for image feature extraction},  
     year = {2021},  
     publisher = {GitHub},  
     journal = {GitHub repository},  
     howpublished = {\url{https://github.com/giakou4/pyfeats}},  
   }  
```

You can convert this BibTeX entry to any citation format using a tool like this: https://www.bibtex.com/c/bibtex-to-mla-converter/

**Comment by korrahman** [comment]
> Thank you for using _pyfeats_. Here is the corrected BibTeX format to cite _pyfeats_:
> 
> ```
> @misc{pyfeats2021giakoumoglou,  
>      author = {Nikolaos Giakoumoglou},  
>      title = {PyFeats: Open-source software for image feature extraction},  
>      year = {2021},  
>      publisher = {GitHub},  
>      journal = {GitHub repository},  
>      howpublished = {\url{https://github.com/giakou4/pyfeats}},  
>    }  
> ```
> 
> You can convert this BibTeX entry to any citation format using a tool like this: https://www.bibtex.com/c/bibtex-to-mla-converter/

thank you so much
